# Capstone Project-1

In [1]:
# Required Libraries:

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# 1. Data Collection:

In [3]:
df = pd.read_csv(r"C:\Users\HP\Desktop\Digi-crome\DigiCrome_Capstone_Project-1\Data\Property_data.csv")

In [4]:
df

,PropertyID,PropertyClass,PropertyZone,PropertyFrontage,PropertySize,Street,Alley,PropertyShape,Elevation,Amenities,...,PoolArea,PoolQC,BoundaryFeatures,AddFeatures,AddVal,SaleMon,SaleYr,SaleType,SaleCondn,PropPrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [5]:
df.head(5)

,PropertyID,PropertyClass,PropertyZone,PropertyFrontage,PropertySize,Street,Alley,PropertyShape,Elevation,Amenities,...,PoolArea,PoolQC,BoundaryFeatures,AddFeatures,AddVal,SaleMon,SaleYr,SaleType,SaleCondn,PropPrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [6]:
df.tail(5)

,PropertyID,PropertyClass,PropertyZone,PropertyFrontage,PropertySize,Street,Alley,PropertyShape,Elevation,Amenities,...,PoolArea,PoolQC,BoundaryFeatures,AddFeatures,AddVal,SaleMon,SaleYr,SaleType,SaleCondn,PropPrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [7]:
df.shape

(1460, 81)

In [8]:
df.columns

Index(['PropertyID', 'PropertyClass', 'PropertyZone', 'PropertyFrontage',
       'PropertySize', 'Street', 'Alley', 'PropertyShape', 'Elevation',
       'Amenities', 'Orientation', 'Grade', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'PropertyStyle', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Roof1Material',
       'Roof2Material', 'ExteriorCladdingType', 'ExteriorCladdingArea',
       'ExterQual', 'ExterCond', 'PropertyFooting', 'BsmntFinish',
       'BsmntMaintenance', 'BsmntVisibility', 'BsmntFinRat1', 'BsmntFinSty1',
       'BsmntFinQual1', 'BsmtFinSF2', 'BsmtUnfSF', 'BsmntSqFtage', 'Heating',
       'HeatingEfficiency', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'Bath1',
       'Bath2', 'BedroomUpLev', 'KitchenUpLev', 'KitchenQual', 'CntRmsUpLev',
       'Functional', 'CntFireplaces', 'QualFireplace', 'BasementType',
       'BasementYrBlt', 'BasementFinish', 'BasementCars', 'BasementSqFootage',
       'BasementQual', 'BasementCond', 'PavedDrive', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'PoolQC', 'BoundaryFeatures', 'AddFeatures', 'AddVal', 'SaleMon',
       'SaleYr', 'SaleType', 'SaleCondn', 'PropPrice'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PropertyID            1460 non-null   int64
 1   PropertyClass         1460 non-null   int64
 2   PropertyZone          1460 non-null   object
 3   PropertyFrontage      1201 non-null   float64
 4   PropertySize          1460 non-null   int64
 5   Street                1460 non-null   object
 6   Alley                 91 non-null     object
 7   PropertyShape         1460 non-null   object
 8   Elevation             1460 non-null   object
 9   Amenities             1460 non-null   object
 10  Orientation           1460 non-null   object
 11  Grade                 1460 non-null   object
 12  Neighborhood          1460 non-null   object
 13  Condition1            1460 non-null   object
 14  Condition2            1460 non-null   object
 15  BldgType              1460 non-null   object
 16  PropertyStyle         1460 non-null   object
 17  OverallQual           1460 non-null   int64
 18  OverallCond           1460 non-null   int64
 19  YearBuilt             1460 non-null   int64
 20  YearRemodAdd          1460 non-null   int64
 21  RoofStyle             1460 non-null   object
 22  RoofMatl              1460 non-null   object
 23  Roof1Material         1460 non-null   object
 24  Roof2Material         1460 non-null   object
 25  ExteriorCladdingType  588 non-null    object
 26  ExteriorCladdingArea  1452 non-null   float64
 27  ExterQual             1460 non-null   object
 28  ExterCond             1460 non-null   object
 29  PropertyFooting       1460 non-null   object
 30  BsmntFinish           1423 non-null   object
 31  BsmntMaintenance      1423 non-null   object
 32  BsmntVisibility       1422 non-null   object
 33  BsmntFinRat1          1423 non-null   object
 34  BsmntFinSty1          1460 non-null   int64
 35  BsmntFinQual1         1422 non-null   object
 36  BsmtFinSF2            1460 non-null   int64
 37  BsmtUnfSF             1460 non-null   int64
 38  BsmntSqFtage          1460 non-null   int64
 39  Heating               1460 non-null   object
 40  HeatingEfficiency     1460 non-null   object
 41  CentralAir            1460 non-null   object
 42  Electrical            1459 non-null   object
 43  1stFlrSF              1460 non-null   int64
 44  2ndFlrSF              1460 non-null   int64
 45  LowQualFinSF          1460 non-null   int64
 46  GrLivArea             1460 non-null   int64
 47  BsmtFullBath          1460 non-null   int64
 48  BsmtHalfBath          1460 non-null   int64
 49  Bath1                 1460 non-null   int64
 50  Bath2                 1460 non-null   int64
 51  BedroomUpLev          1460 non-null   int64
 52  KitchenUpLev          1460 non-null   int64
 53  KitchenQual           1460 non-null   object
 54  CntRmsUpLev           1460 non-null   int64
 55  Functional            1460 non-null   object
 56  CntFireplaces         1460 non-null   int64
 57  QualFireplace         770 non-null    object
 58  BasementType          1379 non-null   object
 59  BasementYrBlt         1379 non-null   float64
 60  BasementFinish        1379 non-null   object
 61  BasementCars          1460 non-null   int64
 62  BasementSqFootage     1460 non-null   int64
 63  BasementQual          1379 non-null   object
 64  BasementCond          1379 non-null   object
 65  PavedDrive            1460 non-null   object
 66  WoodDeckSF            1460 non-null   int64
 67  OpenPorchSF           1460 non-null   int64
 68  EnclosedPorch         1460 non-null   int64
 69  3SsnPorch             1460 non-null   int64
 70  ScreenPorch           1460 non-null   int64
 71  PoolArea              1460 non-null   int64
 72  PoolQC                7 non-null      object
 73  BoundaryFeatures      281 non-null    object
 74  AddFeatures           54 non-null     object
 75  AddVal                1460 non-null   int64
 76  SaleMon               1460 non-null   int64
 77  SaleYr                1460 non-null   int64
 78  SaleType              1460 non-null   object
 79  SaleCondn             1460 non-null   object
 80  PropPrice             1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

# Descriptive Statistics Summary of Data:

In [10]:
print(df.describe())

        PropertyID  PropertyClass  PropertyFrontage   PropertySize  \
count  1460.000000    1460.000000       1201.000000    1460.000000
mean    730.500000      56.897260         70.049958   10516.828082
std     421.610009      42.300571         24.284752    9981.264932
min       1.000000      20.000000         21.000000    1300.000000
25%     365.750000      20.000000         59.000000    7553.500000
50%     730.500000      50.000000         69.000000    9478.500000
75%    1095.250000      70.000000         80.000000   11601.500000
max    1460.000000     190.000000        313.000000  215245.000000

       OverallQual  OverallCond    YearBuilt  YearRemodAdd  \
count  1460.000000  1460.000000  1460.000000   1460.000000
mean      6.099315     5.575342  1971.267808   1984.865753
std       1.382997     1.112799    30.202904     20.645407
min       1.000000     1.000000  1872.000000   1950.000000
25%       5.000000     5.000000  1954.000000   1967.000000
50%       6.000000     5.000000  1973.000000   1994.000000
75%       7.000000     6.000000  2000.000000   2004.000000
max      10.000000     9.000000  2010.000000   2010.000000

       ExteriorCladdingArea  BsmntFinSty1  ...   WoodDeckSF  OpenPorchSF  \
count           1452.000000   1460.000000  ...  1460.000000  1460.000000
mean             103.685262    443.639726  ...    94.244521    46.660274
std              181.066207    456.098091  ...   125.338794    66.256028
min                0.000000      0.000000  ...     0.000000     0.000000
25%                0.000000      0.000000  ...     0.000000     0.000000
50%                0.000000    383.500000  ...     0.000000    25.000000
75%              166.000000    712.250000  ...   168.000000    68.000000
max             1600.000000   5644.000000  ...   857.000000   547.000000

       EnclosedPorch    3SsnPorch  ScreenPorch     PoolArea        AddVal  \
count    1460.000000  1460.000000  1460.000000  1460.000000   1460.000000
mean       21.954110     3.409589    15.060959     2.758904     43.489041
std        61.119149    29.317331    55.757415    40.177307    496.123024
min         0.000000     0.000000     0.000000     0.000000      0.000000
25%         0.000000     0.000000     0.000000     0.000000      0.000000
50%         0.000000     0.000000     0.000000     0.000000      0.000000
75%         0.000000     0.000000     0.000000     0.000000      0.000000
max       552.000000   508.000000   480.000000   738.000000  15500.000000

           SaleMon       SaleYr      PropPrice
count  1460.000000  1460.000000    1460.000000
mean      6.321918  2007.815753  180921.195890
std       2.703626     1.328095   79442.502883
min       1.000000  2006.000000   34900.000000
25%       5.000000  2007.000000  129975.000000
50%       6.000000  2008.000000  163000.000000
75%       8.000000  2009.000000  214000.000000
max      12.000000  2010.000000  755000.000000

[8 rows x 38 columns]

# 2. Data Cleaning: