In [1]:
# Required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load data
df = pd.read_csv(r'C:\Users\HP\Desktop\Digi-crome\DigiCrome_Capstone_Project-1\Data\feature_Property_data.csv')

In [3]:
df.head(5)

,PropertyID,PropertyClass,PropertyFrontage,PropertySize,OverallQual,OverallCond,YearBuilt,YearRemodAdd,ExteriorCladdingArea,BsmntFinSty1,...,SaleCondn_Alloca,SaleCondn_Family,SaleCondn_Normal,SaleCondn_Partial,AgeAtSale,YearsSinceRemodel,TotalBathrooms,TotalSqFootage,QualityScore,GrLivArea_OverallQual
0,1,60,65,8450,7,5,2003,2003,196,706,...,0,0,1,0,5,5,3.5,1860,35,11970
1,2,20,80,9600,6,8,1976,1976,0,978,...,0,0,1,0,31,31,2.5,1546,48,7572
2,3,60,68,11250,7,5,2001,2002,162,486,...,0,0,1,0,7,6,3.5,2220,35,12502
3,4,70,60,9550,7,5,1915,1970,0,216,...,0,0,0,0,91,36,2.0,2257,35,12019
4,5,60,84,14260,8,5,2000,2000,350,655,...,0,0,1,0,8,8,3.5,2688,40,17584

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1430 entries, 0 to 1429
Columns: 268 entries, PropertyID to GrLivArea_OverallQual
dtypes: float64(1), int64(267)
memory usage: 2.9 MB

## Model Selection

In [5]:
X=df.drop('PropPrice',axis=1)
Y=df [['PropPrice']]

In [6]:
X

,PropertyID,PropertyClass,PropertyFrontage,PropertySize,OverallQual,OverallCond,YearBuilt,YearRemodAdd,ExteriorCladdingArea,BsmntFinSty1,...,SaleCondn_Alloca,SaleCondn_Family,SaleCondn_Normal,SaleCondn_Partial,AgeAtSale,YearsSinceRemodel,TotalBathrooms,TotalSqFootage,QualityScore,GrLivArea_OverallQual
0,1,60,65,8450,7,5,2003,2003,196,706,...,0,0,1,0,5,5,3.5,1860,35,11970
1,2,20,80,9600,6,8,1976,1976,0,978,...,0,0,1,0,31,31,2.5,1546,48,7572
2,3,60,68,11250,7,5,2001,2002,162,486,...,0,0,1,0,7,6,3.5,2220,35,12502
3,4,70,60,9550,7,5,1915,1970,0,216,...,0,0,0,0,91,36,2.0,2257,35,12019
4,5,60,84,14260,8,5,2000,2000,350,655,...,0,0,1,0,8,8,3.5,2688,40,17584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1425,1456,60,62,7917,6,5,1999,2000,0,0,...,0,0,1,0,8,7,2.5,2600,30,9882
1426,1457,20,85,13175,6,6,1978,1988,119,790,...,0,0,1,0,32,22,3.0,2825,36,12438
1427,1458,70,66,9042,7,9,1941,2006,0,275,...,0,0,1,0,69,4,2.0,3217,63,16380
1428,1459,20,68,9717,5,6,1950,1996,0,49,...,0,0,1,0,60,14,2.0,2107,30,5390
1429,1460,20,75,9937,5,6,1965,1965,0,830,...,0,0,1,0,43,43,2.5,1682,30,6280

In [7]:
Y

      PropPrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1425     175000
1426     210000
1427     266500
1428     142125
1429     147500

[1430 rows x 1 columns]

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [9]:
# Splitting the data
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=42)

## Training and Model Evaluation

### Random Forest

In [10]:
rf_model = RandomForestRegressor()
rf_model.fit(X_train, Y_train)
rf_y_pred = rf_model.predict(X_test)

In [11]:
score = r2_score(Y_test, rf_y_pred)
print(f'Model r2 score: {score}')

Model r2 score: 0.8717899924338363

### Gradient Boosting Regressor Model

In [12]:
gr_model = GradientBoostingRegressor()
gr_model.fit(X_train, Y_train)
gb_y_pred = gr_model.predict(X_test)

In [13]:
score = r2_score(Y_test, gb_y_pred)
print(f'Model r2 score: {score}')

Model r2 score: 0.8823595507207167

## Apply PCA

In [14]:
# Split data
x_train,x_test,y_train,y_test=train_test_split(X_scaled,Y,test_size=0.2,random_state=42)

In [15]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95) 
x_train_pca = pca.fit_transform(x_train)
x_test_pca = pca.transform(x_test)

### After PCA Random Forest Model

In [16]:
pca_rf_model = RandomForestRegressor()
pca_rf_model.fit(x_train_pca, y_train)
rf_y_pred3 = pca_rf_model.predict(x_test_pca)

In [17]:
score = r2_score(y_test, rf_y_pred3)
print(f'Model r2 score: {score}')

Model r2 score: 0.8647844699461091

### After PCA Gradient Boosting Regressor Model

In [18]:
pca_gr_model = GradientBoostingRegressor()
pca_gr_model.fit(x_train_pca, y_train)
gb_y_pred4 = pca_gr_model.predict(x_test_pca)

In [19]:
score = r2_score(y_test, gb_y_pred4)
print(f'Model r2 score: {score}')

Model r2 score: 0.8912381988942097

## Evaluate each model using MAE and RMSE

In [20]:
#Random Forest Metrics
mae_forest = mean_absolute_error(y_test, rf_y_pred3)
rmse_forest = np.sqrt(mean_squared_error(y_test, rf_y_pred3))
print(f"Random Forest - MAE: {mae_forest}, RMSE: {rmse_forest}")

Random Forest - MAE: 16307.456923076921, RMSE: 24524.265058413395

In [21]:
#Gradient Boosting Regressor Metrics
mae_gradient = mean_absolute_error(y_test, gb_y_pred4)
rmse_gradient = np.sqrt(mean_squared_error(y_test, gb_y_pred4))
print(f"Random Forest - MAE: {mae_gradient}, RMSE: {rmse_gradient}")

Random Forest - MAE: 14672.20726563798, RMSE: 21994.84517830247

## Compare the Models

In [22]:
# Print the metrics for comparison

print("Model Evaluation Results:")
print(f"Random Forest - MAE: {mae_forest:.4f}, RMSE: {rmse_forest:.4f}")
print(f"Gradient Boosting - MAE: {mae_gradient:.4f}, RMSE: {rmse_gradient:.4f}")


# Determine the best model
models = {
    "Random Forest": {"MAE": mae_forest, "RMSE": rmse_forest},
    "Gradient Boosting": {"MAE": mae_gradient, "RMSE": rmse_gradient},
}

best_model = min(models, key=lambda x: models[x]["RMSE"])
print(f"The best model is: {best_model}")

Model Evaluation Results:
Random Forest - MAE: 16307.4569, RMSE: 24524.2651
Gradient Boosting - MAE: 14672.2073, RMSE: 21994.8452
The best model is: Gradient Boosting

## Saving the Best Model

In [23]:
import pickle
import os
directory = r'C:\Users\HP\Desktop\Digi-crome\DigiCrome_Capstone_Project-1'
filename = os.path.join(directory, 'Gradient_Boosting_Regressor.pkl')

# Serialize the model using pickle
with open(filename, 'wb') as file:
    pickle.dump(gb_y_pred4, file)